[package]
name = "des"
version = "0.1.0"
authors = ["Alexey Larionov <alex_osoboe@mail.ru>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [[lib]]

# [[bin]]

[dependencies]
